### ISSUE TITLE
hello-world - no attribute onTrigger

### ISSUE THREAD

**Issue by harry-french** [BowlerHatLLC/feathersui-coconut-samples#1]
## full error
src/Main.hx:19: characters 5-14 : <Button> has no attribute onTrigger
## compile 
openfl test neko
## haxe version
4.1.4
## library versions
actuate: [1.8.9]
assert: [git]
box2d: [1.2.3]
castle: [git]
coconut.data: [0.10.1]
coconut.diffing: [0.2.1]
coconut.feathersui: [1.0.0]
coconut.ui: [0.11.2]
deepnightLibs: 0.0.32 0.0.34 [git]
deepstate: [0.14.1]
feathersui: 1.0.0-alpha.1 1.0.0-alpha.2 [1.0.0-alpha.3]
format: [3.5.0]
hashlink: [0.1.0]
haxe-concurrent: [3.0.0]
haxe-crypto: [0.0.7]
haxe-files: [2.0.0]
haxe-strings: 5.2.4 [6.0.3] git
haxelib: [3.3.0]
heaps: 1.7.0 [git]
HIDE: [0.4.8]
hldx: [1.10.0]
hlopenal: [1.5.0]
hlsdl: [1.10.0]
hscript: 2.3.0 [2.4.0]
html-entities: [1.0.0]
hxargs: [3.0.2]
hxbit: [1.5.0]
hxcpp-debugger: [git]
hxcpp: 4.0.64 4.1.1 [4.1.15]
hxjsonast: [1.0.1]
hxnodejs: 10.0.0 12.0.0 [12.1.0]
json2object: 3.6.4 3.8.0 [3.8.1]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: 2.9.1 7.6.3 7.7.0 [7.8.0]
mconsole: [1.6.0]
mcover: [2.2.2]
mlib: [2.0.3]
munit: [2.3.5]
node-webkit: [1.0.7]
openfl-samples: [8.7.0]
openfl: 3.6.1 8.9.5 8.9.6 8.9.7 [9.0.2]
pony: 1.2.2 1.2.3 1.2.4 1.2.6 1.2.7 1.2.8 [1.3.1]
reaxe: 1.0.2 1.0.3 [1.0.4]
test-adapter: 1.2.6 1.2.8 1.2.9 1.2.10 [dev:/home/bloognoo/.vscode/extensions/vshaxe.haxe-test-adapter-1.2.6/test-adapter]
tink_anon: [0.5.1]
tink_core: [2.0.0-rc.1]
tink_hxx: [0.24.4]
tink_lang: [0.7.0]
tink_macro: [0.21.1]
tink_parse: [0.4.1]
tink_priority: [0.1.4]
tink_pure: [0.5.2]
tink_slice: [0.1.0]
tink_state: [0.11.1]
tink_syntaxhub: [0.4.3]
utest: [1.13.1]
uuid: [2.3.0]
yaml: 1.3.0 2.0.0 [2.0.1]

**Comment by harry-french** [comment]
Oh, and I'm on linux - Ubuntu 18.04

**Comment by joshtynjala** [comment]
You'll need to use the latest Feathers UI source code from Github for now. alpha.3 won't work.

https://feathersui.com/learn/haxe-openfl/prerelease/

**Comment by harry-french** [comment]
OK. Thank you
